// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZTrqIL6RyF-H1Z68vH39lV_RU8tv-SDU',
    appId: '1:366821501404:web:e2ca3702090ff2cb6b8719',
    messagingSenderId: '366821501404',
    projectId: 'login-register-profile-f279b',
    authDomain: 'login-register-profile-f279b.firebaseapp.com',
    storageBucket: 'login-register-profile-f279b.appspot.com',
    measurementId: 'G-NRWYE68RXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4frzVWdzBKsLyJMS0b-vayQuYll7qJwA',
    appId: '1:366821501404:android:e895bbb01324ecb56b8719',
    messagingSenderId: '366821501404',
    projectId: 'login-register-profile-f279b',
    storageBucket: 'login-register-profile-f279b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVf1hEd1sTg_iIW118GWsxNs8TRzAXNB8',
    appId: '1:366821501404:ios:42222902491ce90b6b8719',
    messagingSenderId: '366821501404',
    projectId: 'login-register-profile-f279b',
    storageBucket: 'login-register-profile-f279b.appspot.com',
    iosClientId: '366821501404-ebooqcgo5be0cmqm63qmdkpr0396ljuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegiesterProfile',
  );
}
